### ISSUE TITLE
Code not compiling

### ISSUE THREAD

**Issue by Domosed-gamin** [linnit/fireup#1]
Hi! I love ascii games. I try to build your game and I have error. Please fix it if you have free time. Also please tell me what is license you use for it?

```
qwerty@qwerty:~/Загрузки/fireup-master$ make
gcc ./src/fireup.c ./obj/boxes.o -Wall -Wextra -Wshadow -std=c99 -D_POSIX_C_SOURCE=199309L -g -lncurses -o ./bin/fireup
./obj/boxes.o:(.bss+0x0): multiple definition of `boxes'
/tmp/ccdagAzR.o:(.bss+0x18): first defined here
collect2: error: ld returned 1 exit status
Makefile:8: ошибка выполнения рецепта для цели «all»
make: *** [all] Ошибка 1

```

**Comment by 5quinque** [comment]
Hi,
I'm also having issues compiling. Unfortunately it was a long time ago I worked on this, so don't really have to time to fix it.
There's not currently a license, so feel free to do whatever you like with it.
